general {
    gaps_in = 5
    gaps_out = 33,5,5,5
    border_size = 2
    col.active_border = rgba(c678ddee) rgba(8d78ddee) 45deg
    col.inactive_border = rgba(595959aa)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 12
    active_opacity = 1.0
    inactive_opacity = 1.0
    blur {
        enabled = true
        size = 0
        passes = 5
        vibrancy = 1
    }
}

animations {
    enabled = true
    animation = windows, 1, 3, default
    animation = windowsOut, 1, 3, default, popin 80%
    animation = border, 1, 5, default
    animation = borderangle, 1, 4, default
    animation = fade, 1, 3, default
    animation = workspaces, 1, 3, default
    animation = layers, 1, 0.001, default
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = true
}

splash = false
windowrule = suppress_event maximize, match:class .*
layerrule = blur on, match:namespace gtk-layer-shell
layerrule = blur on, match:namespace rofi
